### PR TITLE
Containerized approach using Podman as default but falling back to Docker if Podman is not present

### PR DESCRIPTION
**Pull request by dnk8n**
I thought I would share in case interesting to you.

It is quite common for less technical lab members to struggle with basic installation instructions.

I have tried to have them in mind when working on a CLI wrapper script, which outsources the heavy lifting to Podman/Docker.

One problem with Docker is the need for root, which they might likely not have unless on their local machine. It is possible to instead use https://podman.io/ (Maintained by Red Hat, and removes the need for root owned Docker daemon process).

There is also an experimental rootless docker (untested but should work)

___

Podman, if installed in rootless mode, allows typical lab members (without root access) to use the wrapper script contained in this PR (`./etm --help` for more info, see notes on how to use it from any directory)

To install podman: https://podman.io/getting-started/installation

Some extra configuration is required for Podman rootless mode. I got it working side-by-side with docker without issue.

To install podman in rootless mode: https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md

  - The main point is to change Default OCI runtime from runc to crun (`/etc/containers/containers.conf`)

Podman is not necessary though, if docker exists on the system it would use docker (note that it will create root owned files, unlike podman)

### CODE REVIEW

**Comment by dnk8n** [comment]
Worth knowing about the shortcomings of rootless mode - https://github.com/containers/podman/blob/master/rootless.md

**Comment by dnk8n** [comment]
[etm_help.pdf](https://github.com/philliplab/EpitopeMatcher/files/5474947/etm_help.pdf)
etm_help

**Comment by philliplab** [comment]
This is awesome - thank you!

**Comment by dnk8n** [comment]
Glad you like it. It proved useful to one of our lab members!

You will notice some options I haven't got round to implementing are present. Possible to extend, but this provides all the low hanging fruit.

Not sure how useful being able to set a custom entrypoint is anymore, because you could really just do it via the shell `etm run ./entrypoint ...`. It would be useful to set an alternate port and to maybe develop alternate images with an image flag. But actually potentially easier to just write a .env file with variables that get loaded.

Future iterations :) Thanks for the merge.

**Pull request merged**
